"""initial

Revision ID: 9360157ab5de
Revises: 
Create Date: 2026-04-07 17:04:08.226474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9360157ab5de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_task_groups',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('task_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['task_group_id'], ['task_groups.id'], ),
    sa.PrimaryKeyConstraint('area_id', 'task_group_id')
    )
    op.create_index('index_area_task_group_id', 'area_tasks', ['task_group_id'], unique=False)
    op.create_index('index_area_task_id', 'area_tasks', ['area_id'], unique=False)
    op.alter_column('area_users', 'role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('OWNER', 'MEMBER', name='roles'),
               existing_nullable=False)
    op.create_index('index_area_user_id', 'area_users', ['user_id'], unique=False)
    op.create_index('index_schedule_id', 'schedules', ['area_task_id'], unique=False)
    op.drop_column('schedules', 'c_provider')
    op.drop_column('schedules', 'c_eventid')
    op.add_column('task_groups', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_taskgroup_name_per_area'), 'task_groups', type_='unique')
    op.drop_constraint(op.f('task_groups_area_id_fkey'), 'task_groups', type_='foreignkey')
    op.create_foreign_key(None, 'task_groups', 'users', ['owner_id'], ['id'])
    op.drop_column('task_groups', 'area_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_groups', sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_groups', type_='foreignkey')
    op.create_foreign_key(op.f('task_groups_area_id_fkey'), 'task_groups', 'areas', ['area_id'], ['id'])
    op.create_unique_constraint(op.f('uq_taskgroup_name_per_area'), 'task_groups', ['name', 'area_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('task_groups', 'owner_id')
    op.add_column('schedules', sa.Column('c_eventid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('schedules', sa.Column('c_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('index_schedule_id', table_name='schedules')
    op.drop_index('index_area_user_id', table_name='area_users')
    op.alter_column('area_users', 'role',
               existing_type=sa.Enum('OWNER', 'MEMBER', name='roles'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index('index_area_task_id', table_name='area_tasks')
    op.drop_index('index_area_task_group_id', table_name='area_tasks')
    op.drop_table('area_task_groups')
    # ### end Alembic commands ###
