"""required auth id or discord id

Revision ID: 34e9807b1a94
Revises: 6238c031db86
Create Date: 2026-03-12 14:03:33.248243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e9807b1a94'
down_revision: Union[str, Sequence[str], None] = '6238c031db86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'areas', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('discord_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'auth0_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['discord_id'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'auth0_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'discord_id')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'owner_id')
    # ### end Alembic commands ###
